### PR TITLE
Optimised SwapBlock, E2I and RotLeft.

### PR DESCRIPTION
**Pull request by sp2432**
Updates improve the performance of CNV0, CNV1, CNLiteV0 and CNVliteV1.

### CODE REVIEW

**Comment by ZedPea** [comment]
Awesome! Are these micro optimizations, or do we see a noticeable change on the CN performance? See https://github.com/turtlecoin/cs-turtlecoin#benchmarking for benchmarking.

**Comment by ZedPea** [comment]
Ah, seems to not pass tests :cry: 

https://ci.appveyor.com/project/RocksteadyTC/cs-turtlecoin/build/1.0.4

**Comment by sp2432** [comment]
Hi Zack,

I got an average of 16% improvement over the 4 CN routines....I missed the
tests, so that might change.
I'll have a look at those now.

Cheers.
Si

**Comment by ZedPea** [comment]
Nope, that's it. We can merge it in now. Thanks for your contribution! We'd love to chat more in #dev_general in Discord if you're interested on making more changes or additions.

**Comment by sp2432** [comment]
It's my first contribution to a project like this, I'm not an expert in any
area but if I can contribute more I will.

Thanks
Si

**Pull request merged**
